import type { CareerPathway } from "./career-schema";

export const careerPathways: CareerPathway[] = [
  {
    id: "embedded-systems-engineer",
    name: "Embedded Systems Engineer",
    description: "Design and develop embedded systems, firmware, and microcontroller applications",
    targetRole: "Embedded Systems Engineer",
    requiredSkills: ["arduino", "c-programming", "circuit-design", "embedded-systems", "microcontrollers"],
    recommendedCourses: ["arduino-basics", "digital-electronics", "embedded-programming"],
    estimatedDuration: "6-12 months",
    difficulty: "advanced",
    averageSalary: {
      entry: 70000,
      mid: 95000,
      senior: 130000,
    },
    milestones: [
      {
        id: "m1",
        title: "Electronics Fundamentals",
        description: "Master basic electronics and circuit design",
        requiredSkills: ["electronics-basics", "circuit-design"],
        courses: ["basics-of-electronics", "circuit-design-basics"],
        completed: false,
      },
      {
        id: "m2",
        title: "Microcontroller Programming",
        description: "Learn Arduino and C programming",
        requiredSkills: ["arduino", "c-programming"],
        courses: ["arduino-basics"],
        completed: false,
      },
      {
        id: "m3",
        title: "Embedded Systems Design",
        description: "Build real-world embedded projects",
        requiredSkills: ["embedded-systems", "microcontrollers"],
        courses: [],
        completed: false,
      },
    ],
  },
  {
    id: "iot-developer",
    name: "IoT Developer",
    description: "Create connected devices and IoT solutions",
    targetRole: "IoT Developer",
    requiredSkills: ["iot", "arduino", "sensors", "wireless-communication", "cloud-integration"],
    recommendedCourses: ["iot-basics", "arduino-basics", "sensors-actuators"],
    estimatedDuration: "4-8 months",
    difficulty: "intermediate",
    averageSalary: {
      entry: 65000,
      mid: 90000,
      senior: 125000,
    },
    milestones: [
      {
        id: "m1",
        title: "IoT Fundamentals",
        description: "Understand IoT concepts and architecture",
        requiredSkills: ["iot"],
        courses: ["iot-basics"],
        completed: false,
      },
      {
        id: "m2",
        title: "Sensor Integration",
        description: "Learn to work with various sensors",
        requiredSkills: ["sensors"],
        courses: ["sensors-actuators"],
        completed: false,
      },
      {
        id: "m3",
        title: "IoT Projects",
        description: "Build complete IoT solutions",
        requiredSkills: ["iot", "cloud-integration"],
        courses: [],
        completed: false,
      },
    ],
  },
  {
    id: "hardware-engineer",
    name: "Hardware Engineer",
    description: "Design electronic hardware and PCB layouts",
    targetRole: "Hardware Engineer",
    requiredSkills: ["circuit-design", "pcb-design", "electronics", "component-selection"],
    recommendedCourses: ["basics-of-electronics", "digital-electronics", "circuit-design-basics"],
    estimatedDuration: "6-12 months",
    difficulty: "advanced",
    averageSalary: {
      entry: 75000,
      mid: 100000,
      senior: 140000,
    },
    milestones: [
      {
        id: "m1",
        title: "Electronics Mastery",
        description: "Deep understanding of electronic principles",
        requiredSkills: ["electronics", "circuit-design"],
        courses: ["basics-of-electronics", "digital-electronics"],
        completed: false,
      },
      {
        id: "m2",
        title: "PCB Design",
        description: "Learn PCB layout and design tools",
        requiredSkills: ["pcb-design"],
        courses: ["circuit-design-basics"],
        completed: false,
      },
      {
        id: "m3",
        title: "Hardware Projects",
        description: "Design and prototype electronic hardware",
        requiredSkills: ["component-selection", "pcb-design"],
        courses: [],
        completed: false,
      },
    ],
  },
  {
    id: "robotics-engineer",
    name: "Robotics Engineer",
    description: "Build and program robots and autonomous systems",
    targetRole: "Robotics Engineer",
    requiredSkills: ["arduino", "robotics", "sensors", "control-systems", "mechanics"],
    recommendedCourses: ["arduino-basics", "sensors-actuators"],
    estimatedDuration: "8-12 months",
    difficulty: "advanced",
    averageSalary: {
      entry: 80000,
      mid: 105000,
      senior: 150000,
    },
    milestones: [
      {
        id: "m1",
        title: "Programming Foundation",
        description: "Master Arduino and sensor programming",
        requiredSkills: ["arduino", "sensors"],
        courses: ["arduino-basics", "sensors-actuators"],
        completed: false,
      },
      {
        id: "m2",
        title: "Control Systems",
        description: "Learn robotics control systems",
        requiredSkills: ["control-systems"],
        courses: [],
        completed: false,
      },
      {
        id: "m3",
        title: "Robotics Projects",
        description: "Build complete robotics solutions",
        requiredSkills: ["robotics", "mechanics"],
        courses: [],
        completed: false,
      },
    ],
  },
  {
    id: "electronics-designer",
    name: "Electronics Designer",
    description: "Design and prototype electronic circuits and systems",
    targetRole: "Electronics Designer",
    requiredSkills: ["electronics", "circuit-design", "arduino", "component-selection"],
    recommendedCourses: ["basics-of-electronics", "circuit-design-basics", "arduino-basics"],
    estimatedDuration: "4-6 months",
    difficulty: "intermediate",
    averageSalary: {
      entry: 60000,
      mid: 85000,
      senior: 115000,
    },
    milestones: [
      {
        id: "m1",
        title: "Circuit Design Basics",
        description: "Learn fundamental circuit design",
        requiredSkills: ["circuit-design"],
        courses: ["basics-of-electronics", "circuit-design-basics"],
        completed: false,
      },
      {
        id: "m2",
        title: "Microcontroller Integration",
        description: "Integrate microcontrollers into designs",
        requiredSkills: ["arduino"],
        courses: ["arduino-basics"],
        completed: false,
      },
      {
        id: "m3",
        title: "Design Portfolio",
        description: "Build a portfolio of circuit designs",
        requiredSkills: ["component-selection", "circuit-design"],
        courses: [],
        completed: false,
      },
    ],
  },
  {
    id: "software-engineer",
    name: "Software Engineer",
    description: "Build scalable software solutions and applications",
    targetRole: "Software Engineer",
    requiredSkills: ["programming", "algorithms", "software-architecture", "database-design", "web-development"],
    recommendedCourses: ["arduino-basics", "block-based-programming"],
    estimatedDuration: "6-12 months",
    difficulty: "advanced",
    averageSalary: {
      entry: 85000,
      mid: 115000,
      senior: 160000,
    },
    milestones: [
      {
        id: "m1",
        title: "Programming Fundamentals",
        description: "Master core programming concepts and logic",
        requiredSkills: ["programming", "algorithms"],
        courses: ["block-based-programming"],
        completed: false,
      },
      {
        id: "m2",
        title: "Software Architecture",
        description: "Learn how to structure scalable applications",
        requiredSkills: ["software-architecture", "database-design"],
        courses: [],
        completed: false,
      },
      {
        id: "m3",
        title: "Full Stack Development",
        description: "Build complete end-to-end applications",
        requiredSkills: ["web-development"],
        courses: [],
        completed: false,
      },
    ],
  },
];
